version: '3.8' 
services: 
 
  journeys-db: 
    image: neo4j:4.4.5-community
    environment:
      NEO4JLABS_PLUGINS: '["apoc"]' 
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
    ports : 
      - "7687:7687" 
      - "7474:7474" 
    container_name: journeys-db 
    volumes: 
      - ./import:/import 
      - ./data:/var/lib/neo4j/data 
      - ./conf:/var/lib/neo4j/conf 

    restart: always 
 
networks: 
  default: 
    name: journeys-web 

