openapi: 3.0.0

info: 
    title: Express API for Journeys App
    version: 1.0.0"
    description: Rest API app made with Express and GraphQL used to retrieve data from a neo4j Database
    license: 
        name: Licensed Under MIT
        url: htpps://spdx.org/licenses/MIT

    contact:
        name: Emmanuel janssens
        email: emmanueljanssens72@gmail.com


paths:
    /journeys:
        $ref: "./schemas/journeys.yml" 

    /journeys/{id}: 
        get:
            summary: Retrieve a journey by id  
            description: Retrieve a journey by id
            parameters:
                -   in: path
                    name: id
                    required: true
                    description: an uuid of the journey
                    schema:
                        type: string
            responses:
                200:
                    description: A simple journey object with all its information
                    content:
                        application/json:
                            schema:
                                $ref: "./schemas/Journey"

    /journeys/{id}/experiences:
        get:
            summary: Retrieve a list of experiences from a journey by id
            description: Retrieve a list of experiences from a journey by id
            responses:
                200:
                    description: A list of experiences belonging to a journey
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id: 
                                        type: string
                                        example: ab880efe-ce1f-4b22-9c42-7276f661803b
                                    experiencesConnection:
                                        type: object
                                        properties:
                                            edges:
                                                type: array
                                                items:                                                   
                                                    $ref: "./schemas/Experience"




                            
 